spring:
  cloud:
    gateway:
      routes:
        - id: car
          uri: lb://CAR-SERVICE
          predicates:
            - Path=/car/**
          filters:
            - StripPrefix=1
            - name: Retry
              args:
                retries: 3
                methods: GET,POST
                backoff:
                  initialInterval: 100ms
                  maxInterval: 2s
                  multiplier: 1.5
            - name: UserAuthentication
              args:
                headerName: Authorization
        - id: motorcycle
          uri: lb://MOTORCYCLE-SERVICE
          predicates:
            - Path=/motorcycle/**
          filters:
            - StripPrefix=1
            - name: Retry
              args:
                retries: 3
                methods: GET,POST
                backoff:
                  initialInterval: 100ms
                  maxInterval: 2s
                  multiplier: 1.5
            - name: UserAuthentication
              args:
                headerName: Authorization
        - id: dealership
          uri: lb://DEALERSHIP
          predicates:
            - Path=/dealership/**
          filters:
            - StripPrefix=1
            - name: UserAuthentication
              args:
                headerName: Authorization
